### ISSUE TITLE
Google Dialer reports device as "unsupported"

### ISSUE THREAD

**Issue by Simone98RC** [Magisk-Modules-Repo/google-framework-magisk#1]
I'm (obviously) running latest v1.1 of _Google Framework_ module.
The Google Dialer **is shown as unsupported** (when **it's working properly at all**).
I've tried to reinstall the app and the module itself, even to wipe cache and do a full reinstallation of Magisk (with both v14.6b and v15.0), **same situation**.
My device is a **Oneplus 3**, the issue persists both in **OxygenOS v5.0.0** and **Open Beta 28**.

To help you, **I've attached** the [issue_stuff.zip](https://github.com/Magisk-Modules-Repo/google-framework-magisk/files/1591130/issue_stuff.zip) file, that includes:

* Screenshot of the warning dialog;
* Logcat (in Info Mode) related to Google Dialer;
* Latest _Dialer Framework_ files included with _OpenGapps 20171228-stock-8.0-arm64_, **to make a comparison** with the framework files provided with this module.

![screenshot_20171228-122425](https://user-images.githubusercontent.com/5165836/34409999-79f8983e-ebcd-11e7-8070-dc5c4364411f.jpg)

**Comment by Maxiride** [comment]
I'm not having the exact same issue, but after installing the module I can't install the dialer from the Google play store as claimed in the description. Might the two situation be correlated?

**Comment by Maxiride** [comment]
I'm not having the exact same issue, but after installing the module I can't install the dialer from the Google play store as claimed in the description. Might the two situation be correlated?

**Comment by Maxiride** [comment]
I'm not having the exact same issue, but after installing the module I can't install the dialer from the Google play store as claimed in the description. Might the two situation be correlated?

**Comment by Maxiride** [comment]
I'm not having the exact same issue, but after installing the module I can't install the dialer from the Google play store as claimed in the description. Might the two situation be correlated?

**Comment by Maxiride** [comment]
I'm not having the exact same issue, but after installing the module I can't install the dialer from the Google play store as claimed in the description. Might the two situation be correlated?

**Comment by Maxiride** [comment]
I'm not having the exact same issue, but after installing the module I can't install the dialer from the Google play store as claimed in the description. Might the two situation be correlated?

**Comment by Maxiride** [comment]
I'm not having the exact same issue, but after installing the module I can't install the dialer from the Google play store as claimed in the description. Might the two situation be correlated?

**Comment by Maxiride** [comment]
I'm not having the exact same issue, but after installing the module I can't install the dialer from the Google play store as claimed in the description. Might the two situation be correlated?

**Comment by Maxiride** [comment]
Same issue here, same device but OOs 5.0.1

**Comment by Maxiride** [comment]
Same issue here, same device but OOs 5.0.1

**Comment by Maxiride** [comment]
Same issue here, same device but OOs 5.0.1

**Comment by gpolydoros** [comment]
Same issue, OnePlus 5 on OOS 5.0.1...

**Comment by w7co37** [comment]
Dame Issue, Moto G4 Plus Stock 7.0

**Comment by rufik** [comment]
@P1N2O It's easy to solve - you can use files from latest GApps and that's all :)

**Comment by gpolydoros** [comment]
Yeah, I later found out that all it really needed in order to stop complaining was /system/etc/sysconfig/dialer.experience.xml. :)

**Comment by Maxiride** [comment]
@gpolydoros  could you elaborate more specifically what should be done to fix it pleases? I didn't understand what I should do with that file you mentioned.

**Comment by gpolydoros** [comment]
Sure. Every time Google Dialer starts up, it looks for dialer_experience.xml under /system/etc/sysconfig. If it can't find it there, it complains that your device is not supported.

So, to overcome this issue, you'll need to download the file I've attached below, rename it to dialer_experience.xml (Github didn't allow me to upload it as XML), and then use Root Explorer or a similar root file manager to copy this file to /system/etc/sysconfig. As always, remember to set the file's permissions to rw-r--r-- (0644). Force-stop and start Google Dialer again, and voila, no more unsupported notifications!

[dialer_experience.txt](https://github.com/Magisk-Modules-Repo/google-framework-magisk/files/1747822/dialer_experience.txt)

**Comment by Maxiride** [comment]
Kinda solves part of the issue for me.

After copying the file and setting the permissions and terminating the dialer app, the first launch of Google dialer still shows the error message, if I don't close the app (from the recent apps menu) subsequent app launches do not show the error (previously it was shown every time).

If I close the dialer from the recent apps the dialer then shows the error on first launch and after a reboot the file is somehow automatically removed from the directory.

Are there further debugging information I could provide?

**Comment by gpolydoros** [comment]
That's strange. Could you try removing the framework **and** Google Dialer and then flashing the attached Magisk module? This is the exact same module I'm using on OOS 5.0.2 and it works without any errors.

[Magisk-GoogleDialer.zip](https://github.com/Magisk-Modules-Repo/google-framework-magisk/files/1748060/Magisk-GoogleDialer.zip)

**Comment by rignaneseleo** [comment]
I've the same error, also if I put the file dialer_experience.txt in the folder.
I've the OP 3T with OOS 5.0.1. I didn't have this problem before.
Are there any solutions?

**Comment by P1N2O** [comment]
**Fixed**

**Comment by kevin71246** [comment]
I copied dialer_experience.xml -> /system/etc/sysconfig/dialer_experience.xml. Root Browser couldn't set the permissions. So I flashed a dummy update via FlashFire using the read/write system option.  Then I copied in the file and checked the permissions were correct on the file.  I restarted the phone.  I still have this issue and the file no longer exists in /system/etc/sysconfig/. Any ideas?  Thanks!

**Comment by P1N2O** [comment]
> I copied dialer_experience.xml -> /system/etc/sysconfig/dialer_experience.xml. Root Browser couldn't set the permissions. So I flashed a dummy update via FlashFire using the read/write system option. Then I copied in the file and checked the permissions were correct on the file. I restarted the phone. I still have this issue and the file no longer exists in /system/etc/sysconfig/. Any ideas? Thanks!

1. Are you using Magisk and This Module?

If YES, why is it that you are manually copy-pasting?
